# Generated by Django 3.2 on 2023-04-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(max_length=200),
        ),
    ]
