# Generated by Django 3.2 on 2023-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_categoria_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='fecha de registro'),
        ),
    ]
